const assert = require('node:assert/strict')
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright')
const origin = 'http://127.0.0.1:18880'
;(async () => {
  const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH, headless: true })
  try {
    const context = await browser.newContext({ viewport: { width: 1280, height: 900 }, serviceWorkers: 'block' })
    assert.equal((await context.request.post(origin+'/api/method/login', {
      form: { usr: 'hr@qa.invalid', pwd: 'Synthetic-QA-Only!9842-Browser' } })).status(), 200)
    const page = await context.newPage(), errors = []
    page.on('pageerror', e => { errors.push(e.message); console.log('DESK_ERROR', e.stack) })
    await page.goto(origin+'/desk/admin-reviews/project-timesheets', { waitUntil: 'domcontentloaded', timeout: 60000 })
    await page.getByRole('columnheader', { name: 'Review Status', exact: true }).waitFor({ timeout: 45000 })
    assert.equal(await page.getByRole('columnheader', { name: /Week status/i }).count(), 0)
    const tableRows = page.locator('.admin-reviews-page .admin-reviews-table tbody tr')
    await tableRows.nth(49).waitFor()
    const firstPage = await tableRows.allTextContents()
    assert.ok(firstPage.every(row => row.includes('Pending')), 'Old submitted approvals must precede newer drafts')
    await page.screenshot({ path: '/private/tmp/hrms-queue-desk-desktop.png', fullPage: false })
    await page.getByRole('button', { name: 'Load more', exact: true }).click()
    await tableRows.nth(99).waitFor()
    assert.deepEqual((await tableRows.allTextContents()).slice(0, 50), firstPage)
    assert.equal(await tableRows.locator('input[type=checkbox]:not(:disabled)').count(), 68)
    await tableRows.first().getByRole('button', { name: 'Review entries' }).click()
    const dialog = page.locator('.modal.show')
    await dialog.getByText('Week Status:', { exact: true }).waitFor()
    await dialog.getByText('Awaiting project review', { exact: true }).waitFor()
    await dialog.getByText('Review Status:', { exact: true }).waitFor()
    await dialog.locator('.modal-header .btn-modal-close').click()
    await page.getByRole('button', { name: 'History', exact: true }).click()
    await page.getByText('20 of 20 sections', { exact: true }).waitFor()
    assert.equal(await tableRows.locator('input[type=checkbox]:not(:disabled)').count(), 0)
    for (const width of [1280, 390]) {
      await page.setViewportSize({ width, height: 900 })
      await page.screenshot({ path: '/private/tmp/hrms-queue-desk-'+width+'.png', fullPage: true })
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
    }
    const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, colorScheme: 'dark', serviceWorkers: 'block' })
    assert.equal((await mobile.request.post(origin+'/api/method/login', {
      form: { usr: 'lead@qa.invalid', pwd: 'Synthetic-QA-Only!9842-Browser' } })).status(), 200)
    const hrms = await mobile.newPage()
    hrms.on('pageerror', e => { errors.push(e.message); console.log('HRMS_ERROR', e.stack) })
    await hrms.goto(origin+'/hrms/project-timesheets', { waitUntil: 'domcontentloaded', timeout: 60000 })
    await hrms.locator('article').nth(49).waitFor({ timeout: 30000 })
    const dismiss = hrms.getByRole('button', { name: 'Not now', exact: true })
    if (await dismiss.isVisible()) await dismiss.click()
    assert.equal(await hrms.locator('article').getByText(/Week:/).count(), 0)
    const firstCards = await hrms.locator('article').allTextContents()
    assert.ok(firstCards.every(row => row.includes('Pending')))
    await hrms.screenshot({ path: '/private/tmp/hrms-queue-mobile-dark.png', fullPage: false })
    await hrms.getByRole('button', { name: 'Load more', exact: true }).click()
    await hrms.locator('article').nth(99).waitFor()
    assert.deepEqual((await hrms.locator('article').allTextContents()).slice(0, 50), firstCards)
    await hrms.locator('article').first().locator('button').first().click()
    await hrms.getByText('Week Status: Project review', { exact: true }).waitFor()
    assert.equal(await hrms.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
    await hrms.goto(origin+'/hrms/timesheets/timer', { waitUntil: 'domcontentloaded' })
    await hrms.getByRole('button', { name: 'Retry', exact: true }).waitFor()
    const state = async () => {
      const csrf = await hrms.evaluate(() => window.csrf_token)
      const response = await mobile.request.post(origin+'/api/method/hrms.api.timer_state.get_state', {
        headers: { 'X-Frappe-CSRF-Token': csrf } })
      assert.equal(response.status(), 200); return (await response.json()).message
    }
    const before = await state()
    if (!before.last_error) throw new Error('Reseed synthetic Retry fixture before running browser acceptance')
    await hrms.getByRole('button', { name: 'Retry', exact: true }).click()
    await hrms.getByRole('button', { name: 'Retry', exact: true }).waitFor({ state: 'hidden' })
    const after = await state()
    assert.equal(after.timer.startTime, before.timer.startTime)
    assert.equal(after.timer.form.project, before.timer.form.project)
    assert.equal(after.timer.segments.length, 0); assert.equal(after.last_error, null)
    const worker = await browser.newContext({ viewport: { width: 1280, height: 900 }, serviceWorkers: 'block' })
    assert.equal((await worker.request.post(origin+'/api/method/login', {
      form: { usr: 'worker@qa.invalid', pwd: 'Synthetic-QA-Only!9842-Browser' } })).status(), 200)
    const home = await worker.newPage()
    await home.goto(origin+'/hrms/home', { waitUntil: 'domcontentloaded' })
    await home.getByRole('link', { name: 'My Timesheets', exact: true }).waitFor({ timeout: 30000 })
    assert.equal(await home.getByRole('link', { name: 'Team Timesheets', exact: true }).count(), 0)
    assert.equal(await home.getByText('Team hours', { exact: true }).count(), 0)
    await page.goto(origin+'/desk/admin-reviews', { waitUntil: 'domcontentloaded' })
    await page.getByRole('link', { name: 'HR Weekly Timesheet Review', exact: true }).waitFor()
    const reviewLinks = await page.locator('.admin-reviews-section').first().locator('a').allTextContents()
    assert.match(reviewLinks[0], /HR Weekly/); assert.match(reviewLinks[1], /Team Timesheets/)
    await page.setViewportSize({ width: 1280, height: 900 })
    await page.goto(origin+'/desk/admin-reviews/hr-timesheets', { waitUntil: 'domcontentloaded' })
    await page.getByRole('columnheader', { name: 'Final approval', exact: true }).waitFor()
    const hrRows = page.locator('.admin-reviews-page tbody tr')
    const ready = hrRows.filter({ hasText: 'Ready to finalize' })
    const blocked = hrRows.filter({ hasText: 'Awaiting project review' })
    assert.ok(await ready.count() > 0); assert.ok(await blocked.count() > 0)
    await blocked.first().getByRole('button', { name: 'Review entries' }).click()
    await dialog.getByText('Project and team reviews must be complete before HR can finalize this week.', { exact: true }).waitFor()
    assert.equal(await dialog.getByRole('button', { name: 'Finalize week', exact: true }).count(), 0)
    await dialog.locator('.modal-header .btn-modal-close').click()
    await ready.first().getByRole('button', { name: 'Review entries' }).click()
    await dialog.getByText('Project reviews complete. HR approval is still required.', { exact: true }).waitFor()
    await dialog.getByRole('button', { name: 'Finalize week', exact: true }).click()
    const confirmation = page.locator('.modal.show').filter({ hasText: 'Give final HR approval?' })
    await confirmation.getByText(/This locks the entire week and moves it to history/).waitFor()
    await page.screenshot({ path: '/private/tmp/hrms-final-approval-desktop.png', fullPage: false })
    await page.setViewportSize({ width: 390, height: 844 })
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
    await page.screenshot({ path: '/private/tmp/hrms-final-approval-mobile.png', fullPage: false })
    await confirmation.locator('.modal-header .btn-modal-close').click()
    await dialog.locator('.modal-header .btn-modal-close').click()
    await page.setViewportSize({ width: 1280, height: 900 })
    await page.goto(origin+'/desk/admin-reviews/time-history', { waitUntil: 'domcontentloaded' })
    await page.getByRole('button', { name: 'Apply filters', exact: true }).waitFor()
    await page.getByText('Recorded hours', { exact: true }).first().waitFor()
    await page.locator('#hrms-admin-reviews-style').waitFor({ state: 'attached' })
    await page.getByRole('columnheader', { name: 'Finalized', exact: true }).waitFor()
    await page.getByRole('columnheader', { name: 'Awaiting HR approval', exact: true }).waitFor()
    await page.getByText('Hours by week status', { exact: true }).waitFor()
    await page.getByText('Finalized hours', { exact: true }).waitFor()
    const filterOptions = await page.locator('.admin-history-filters select').first().locator('option').allTextContents()
    assert.ok(filterOptions.includes('Finalized')); assert.ok(filterOptions.includes('Legacy submitted'))
    const filterValues = await page.locator('.admin-history-filters select').first().locator('option').evaluateAll(options => options.map(option => option.value))
    assert.deepEqual(filterValues, ['', 'Draft', 'Pending Project Approval', 'Pending HR Review', 'Correction Required', 'Closed', 'Submitted'])
    await page.waitForFunction(() => {
      const fields = [...document.querySelectorAll('.admin-history-filters input, .admin-history-filters select')].filter(e => e.offsetWidth)
      return fields.length >= 7 && fields.every(e => e.getBoundingClientRect().width >= 160)
    })
    await page.screenshot({ path: '/private/tmp/hrms-history-styled-desktop.png', fullPage: true })
    assert.deepEqual(errors, [])
    console.log('QUEUE_BROWSER_OK: single status, pagination priority, final approval readiness and confirmation, whole-week history labels, read-only history, no overflow, functional timer retry, lead-only navigation, home order and full-width report filters')
  } finally { await browser.close() }
})().catch(e => { console.error(e); process.exitCode = 1 })
